version: 1
formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/project.log
loggers:
  hackernews_trends:
    level: DEBUG
    handlers: [console, file_handler]
    propagate: no
root:
  level: DEBUG
  handlers: [console, file_handler]
